# configs/data_config.yaml
dataset:
  name: "UTKFace"
  source: "https://www.kaggle.com/datasets/jangedoo/utkface-new"
  
  paths:
    raw: "data/raw/UTKFace"
    processed: "data/processed"
  
  total_images: 23000
  sample_size: 5000  # Nombre utilis√© pour training
  
  split:
    train: 0.8  # 4000 images
    val: 0.2    # 1000 images
  
  labels:
    format: "[age]_[gender]_[race]_[datetime].jpg"
    age_ranges:
      bebe: [0, 2]
      enfant: [3, 12]
    gender_map:
      0: "homme"
      1: "femme"

augmentation:
  train:
    - RandomHorizontalFlip
    - RandomRotation: 10
    - ColorJitter:
        brightness: 0.1
  
  validation:
    - Resize: 224
    - Normalize