dataset:
  name: "UTKFace"
  kaggle_dataset: "jangedoo/utkface-new"
  max_samples: 5000
  classes:
    - "bebe"      # 0-2 ans
    - "enfant"    # 3-12 ans
    - "femme"     # 13+ ans, genre f√©minin
    - "homme"     # 13+ ans, genre masculin

preprocessing:
  image_size: [224, 224]
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  augmentation:
    rotation_range: 15
    horizontal_flip: true
    brightness_range: [0.8, 1.2]
