# configs/model_config.yaml
model:
  name: "ResNet50"
  architecture: "resnet50"
  num_classes: 4
  classes:
    - bebe
    - enfant
    - femme
    - homme
  
  pretrained: false
  weights_path: "models/artifacts/best_model.pth"

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  optimizer: "Adam"
  
  scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.5
    patience: 2
    min_lr: 1e-7

preprocessing:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

class_weights:
  bebe: 3.876
  enfant: 3.497
  femme: 0.615
  homme: 0.547